export const SCANNER_MARKETS = [
  { val: "be", txt: "⭐ BULLSEYE" },
  { val: "chn", txt: "⭐ CHINAPOOLS" },
  { val: "hklt", txt: "⭐ HONGKONG LOTTO" },
  { val: "hkg", txt: "⭐ HONGKONG POOLS" },
  { val: "jpn", txt: "⭐ JAPAN" },
  { val: "cmb2", txt: "⭐ MAGNUM CAMBODIA" },
  { val: "ncd", txt: "⭐ NORTH CAROLINA DAY" },
  { val: "sgp", txt: "⭐ SGP | SINGAPORE" },
  { val: "sdlt", txt: "⭐ SYDNEY LOTTO" },
  { val: "syd", txt: "⭐ SYDNEYPOOLS" },
  { val: "twn", txt: "⭐ TAIWAN" },
  { val: "clf", txt: "California" },
  { val: "cd", txt: "Connecticut Day" },
  { val: "cn", txt: "Connecticut Night" },
  { val: "fle", txt: "Florida Evening" },
  { val: "flm", txt: "Florida Midday" },
  { val: "gge", txt: "Georgia Evening" },
  { val: "ggm", txt: "Georgia Midday" },
  { val: "ggn", txt: "Georgia Night" },
  { val: "gm5", txt: "Germany Plus5" },
  { val: "ine", txt: "Illinois Evening" },
  { val: "inm", txt: "Illinois Midday" },
  { val: "ide", txt: "Indiana Evening" },
  { val: "idm", txt: "Indiana Midday" },
  { val: "kye", txt: "Kentucky Evening" },
  { val: "kym", txt: "Kentucky Midday" },
  { val: "mle", txt: "Maryland Evening" },
  { val: "mlm", txt: "Maryland Midday" },
  { val: "mge", txt: "Michigan Evening" },
  { val: "mgm", txt: "Michigan Midday" },
  { val: "mse", txt: "Missouri Evening" },
  { val: "msm", txt: "Missouri Midday" },
  { val: "mqn", txt: "Morocco Quatro 03:00 Wib" },
  { val: "mqd", txt: "Morocco Quatro 18:00 Wib" },
  { val: "mqe", txt: "Morocco Quatro 21:00 Wib" },
  { val: "mqmn", txt: "Morocco Quatro 23:59 Wib" },
  { val: "nje", txt: "New Jersey Evening" },
  { val: "njm", txt: "New Jersey Midday" },
  { val: "nye", txt: "New York Evening" },
  { val: "nym", txt: "New York Midday" },
  { val: "nce", txt: "North Carolina Evening" },
  { val: "og1", txt: "Oregon 04:00 Wib" },
  { val: "og4", txt: "Oregon 07:00 Wib" },
  { val: "og7", txt: "Oregon 10:00 Wib" },
  { val: "og10", txt: "Oregon 13:00 Wib" },
  { val: "ps", txt: "Pcso" },
  { val: "te", txt: "Tennesse Evening" },
  { val: "tmd", txt: "Tennesse Midday" },
  { val: "tm", txt: "Tennesse Morning" },
  { val: "txd", txt: "Texas Day" },
  { val: "txe", txt: "Texas Evening" },
  { val: "txm", txt: "Texas Morning" },
  { val: "txn", txt: "Texas Night" },
  { val: "mce", txt: "Toto Macau 00" },
  { val: "mca", txt: "Toto Macau 13" },
  { val: "mcb", txt: "Toto Macau 16" },
  { val: "mcc", txt: "Toto Macau 19" },
  { val: "mcd", txt: "Toto Macau 22" },
  { val: "mcf", txt: "Toto Macau 23" },
  { val: "vd", txt: "Virginia Day" },
  { val: "vn", txt: "Virginia Night" },
  { val: "wdce", txt: "Washington Dc Evening" },
  { val: "wdcm", txt: "Washington Dc Midday" },
  { val: "wcs", txt: "Wisconsin Evening" },
];

export const SCANNER_TARGETS = [
  { val: "cb", txt: "colok bebas (cb)" },
  { val: "ai", txt: "ai 2d belakang" },
  { val: "aid", txt: "ai 2d depan" },
  { val: "ait", txt: "ai 2d tengah" },
  { val: "a", txt: "as (a)" },
  { val: "c", txt: "cop (c)" },
  { val: "k", txt: "kepala (k)" },
  { val: "e", txt: "ekor (e)" },
  { val: "j", txt: "jumlah 2d" },
  { val: "jt", txt: "jumlah tengah" },
  { val: "jd", txt: "jumlah depan" },
  { val: "s", txt: "shio" },
  { val: "st", txt: "shio tengah" },
  { val: "sd", txt: "shio depan" },
  { val: "ai3d", txt: "ai 3d" },
  { val: "ke", txt: "kepala ekor (ke)" },
];

export const DIGIT_OPTIONS = [
  { val: 1, txt: "1 DIGIT" },
  { val: 2, txt: "2 DIGIT" },
  { val: 3, txt: "3 DIGIT" },
  { val: 4, txt: "4 DIGIT" },
  { val: 5, txt: "5 DIGIT" },
  { val: 6, txt: "6 DIGIT" },
  { val: 7, txt: "7 DIGIT" },
  { val: 8, txt: "8 DIGIT" },
  { val: 9, txt: "9 DIGIT" },
];

export const LIMIT_OPTIONS = Array.from({ length: 147 }, (_, i) => i + 4).map((n) => ({
  val: n,
  txt: `${n} BRS`,
}));

export const PATAH_OPTIONS = Array.from({ length: 11 }, (_, i) => i).map((n) => ({
  val: n,
  txt: `${n} ZNK`,
}));

export const MAX_RUMUS_OPTIONS = [
  { val: 1, txt: "CARI 1 RMS" },
  { val: 2, txt: "CARI 2 RMS" },
  { val: 3, txt: "CARI 3 RMS" },
  { val: 4, txt: "CARI 4 RMS" },
  { val: 5, txt: "CARI 5 RMS" },
  { val: 10, txt: "CARI 10 RMS" },
  { val: 20, txt: "CARI 20 RMS" },
  { val: 30, txt: "CARI 30 RMS" },
];

export const DAY_OPTIONS = [
  { val: "", txt: "-- SEMUA HARI --" },
  { val: "Senin", txt: "SENIN" },
  { val: "Selasa", txt: "SELASA" },
  { val: "Rabu", txt: "RABU" },
  { val: "Kamis", txt: "KAMIS" },
  { val: "Jumat", txt: "JUMAT" },
  { val: "Sabtu", txt: "SABTU" },
  { val: "Minggu", txt: "MINGGU" },
];

export const TYPE_MAP = {
  ai: "AI",
  ait: "AIT",
  aid: "AID",
  cb: "CB",
  s: "SHIO",
  st: "ST",
  sd: "SD",
  j: "JML",
  jt: "JTT",
  jd: "JDD",
  a: "AS",
  c: "COP",
  k: "KEP",
  e: "EKR",
  ai3d: "AI3D",
  ke: "K/E",
};
